# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addCoffee.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class add_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(486, 326)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 471, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.id = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 0, 1, 1, 1)
        self.sort = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.sort.setObjectName("sort")
        self.gridLayout.addWidget(self.sort, 1, 1, 1, 1)
        self.hot = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hot.setObjectName("hot")
        self.gridLayout.addWidget(self.hot, 2, 1, 1, 1)
        self.type = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 3, 1, 1, 1)
        self.tasty = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tasty.setObjectName("tasty")
        self.gridLayout.addWidget(self.tasty, 4, 1, 1, 1)
        self.price = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.price.setMaximum(999999999)
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 5, 1, 1, 1)
        self.volume = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.volume.setMaximum(999999999)
        self.volume.setObjectName("volume")
        self.gridLayout.addWidget(self.volume, 6, 1, 1, 1)
        self.add_coffee = QtWidgets.QPushButton(Form)
        self.add_coffee.setGeometry(QtCore.QRect(20, 290, 451, 23))
        self.add_coffee.setObjectName("add_coffee")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Объём упаковки"))
        self.label_2.setText(_translate("Form", "Название сорта"))
        self.label.setText(_translate("Form", "ID"))
        self.label_3.setText(_translate("Form", "Степень обжарки"))
        self.label_4.setText(_translate("Form", "Молотый/в зернах"))
        self.label_5.setText(_translate("Form", "Описание вкуса"))
        self.label_6.setText(_translate("Form", "Цена"))
        self.add_coffee.setText(_translate("Form", "Добавить"))
